---
blank_issues_enabled: false
contact_links:
  - name: Ask a question or start a discussion
    url: https://github.com/mfussenegger/nvim-jdtls/discussions
    about: Use the Github discussions feature
